# Generated by Django 2.2.5 on 2019-11-23 16:19

import TasksDTY.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDTY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_number', models.IntegerField()),
                ('year', models.CharField(max_length=4)),
                ('date', models.DateField()),
                ('report_damage', models.TextField()),
                ('tech_diagnosis', models.TextField()),
                ('more_info', models.TextField(blank=True)),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('without_tech_report', models.BooleanField(default=False)),
                ('scanned_dty', models.FileField(blank=True, null=True, upload_to='scannedDTY/%Y/%m/%d', validators=[TasksDTY.validators.validate_file_extension])),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.Client')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departments.Department')),
            ],
            options={
                'unique_together': {('code_number', 'year')},
            },
        ),
    ]
