# Generated by Django 2.2.5 on 2019-11-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TasksDTY', '0002_auto_20191128_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdty',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
