# Generated by Django 2.2.5 on 2019-11-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('app', models.CharField(choices=[('1', 'Εργασίες'), ('2', 'Τεχνικές Εκθέσεις')], max_length=1)),
            ],
            options={
                'unique_together': {('name', 'app')},
            },
        ),
    ]
