# Generated by Django 2.2.5 on 2019-11-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='app',
            field=models.CharField(choices=[(1, 'Εργασίες'), (2, 'Τεχνικές Εκθέσεις')], default=1, max_length=1),
        ),
    ]
