# Generated by Django 2.2.5 on 2019-11-23 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TasksDTY', '0001_initial'),
        ('Devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('spare_parts', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('generate_pdf', models.BooleanField(default=False)),
                ('pdf', models.FileField(null=True, upload_to='techReports/%Y/%m/%d')),
                ('sent', models.BooleanField(default=False)),
                ('task_dty_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_report', to='TasksDTY.TaskDTY')),
                ('type_of_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Devices.Device')),
            ],
        ),
    ]
