# Generated by Django 2.2.5 on 2019-11-23 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=65)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=120)),
                ('info', models.TextField(blank=True)),
                ('responsible', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'unique_together': {('last_name', 'first_name')},
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='Clients.Client')),
            ],
        ),
    ]
