# Generated by Django 2.2.5 on 2019-11-23 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
        ('Techs', '0001_initial'),
        ('Devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assignment', models.DateTimeField(auto_now_add=True)),
                ('report_damage', models.TextField()),
                ('tech_diagnosis', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('1', 'Σε εκκρεμότητα'), ('2', 'Σε επισκευή'), ('3', 'Ολοκληρωμένες')], default='1', max_length=1)),
                ('date_completion', models.DateTimeField(null=True)),
                ('ip', models.CharField(blank=True, max_length=15)),
                ('spare_parts', models.TextField(blank=True)),
                ('spare_parts_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('task_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('observations', models.TextField(blank=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.Client')),
                ('tech_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Techs.Tech')),
                ('type_of_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Devices.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefings', to='Tasks.Task')),
            ],
        ),
    ]
